substitutions:
  _REGION: us-central1
  _REPO: cicd-lab-repo
  _CLUSTER: gke-cicd-cluster
  _ZONE: us-central1-c

options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/flask-app:$SHORT_SHA', 'app'
    ]

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/flask-app:$SHORT_SHA'
    ]

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - -c
    - |
      sed "s#IMAGE_URL#$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/flask-app:$SHORT_SHA#g" Manifests/deployment.yaml > Manifests/deployment.tmp.yaml
      gcloud container clusters get-credentials $_CLUSTER --zone $_ZONE
      kubectl apply -f Manifests/

images:
- '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/flask-app:$SHORT_SHA'

